language: php
 
php:
  - 5.3
  - 5.4
 
before_script:
  - pecl install mongo
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - wget http://getcomposer.org/composer.phar
  - php composer.phar --dev install
  - phpunit
